### ISSUE TITLE
Automatic release of tags from Travis to npm

### ISSUE THREAD

**Issue by PowerKiKi** [HaithemMosbahi/ngx-avatar#92]
Following this https://github.com/HaithemMosbahi/ngx-avatar/pull/91#issuecomment-613821331, it would be nice to have automatic release of tags from Travis to npm to reduce bus factor for this project.

Here is an example on how to automatically publish tags as release which should be easy to adapt for this lib. But I cannot create a PR for it since I don't know the credentials to be encoded: https://github.com/Ecodev/fab-speed-dial/blob/123e63c7faeef1d469618dcefb4a111d82fc817f/.travis.yml#L32-L47

So, to copy tag version into our package, `package.json` would look like:

```json
{
  "scripts": {
    "postbuild": "node scripts/copy-artifacts.js && cd dist/ngx-avatar && git describe --tags --always | xargs npm version --no-git-tag-version",
  }
}
```

And for Travis to actually pusblish, `.travis.yml` would be similar to:

```
    - stage: publish npm package
      if: tag is present
      script:
        - npm run build
      before_deploy:
        - rm .gitignore
        - cd dist/ngx-avatar
      deploy:
        provider: npm
        edge: true
        email:
          secure: YOUR ENCRYPTED EMAIL HERE
        api_token:
          secure: YOUR ENCRYPTED API TOKEN HERE
        on:
          tags: true
```
